import {
  IconAffiliate,
  IconArrowDownRight,
  IconArrowRoundaboutLeft,
  IconArrowUpLeft,
  IconBook,
  IconBrandGithub,
  IconBrandGoogle,
  IconCards,
  IconChalkboard,
  IconCircleOff,
  IconDashboard,
  IconLoader2,
  IconLogout2,
  IconMail,
  IconMaximize,
  IconMenu,
  IconPlayerPause,
  IconPlayerPlay,
  IconSearch,
  IconSmartHome,
  IconTableFilled,
  IconUserFilled,
  IconUsers,
  IconX,
  TablerIconsProps,
} from "@tabler/icons-react"

export const Icons = {
  Play: IconPlayerPlay,
  Menu: IconMenu,
  Pause: IconPlayerPause,
  FullScreen: IconMaximize,
  Email: IconMail,
  X: IconX,
  Loader: IconLoader2,
  Spinner: IconLoader2,
  Icon: IconCards,
  Home: IconSmartHome,
  About: IconArrowRoundaboutLeft,
  Document: IconBook,
  School: IconChalkboard,
  Contact: IconAffiliate,
  Github: IconBrandGithub,
  Google: IconBrandGoogle,
  SignatureArrow: IconArrowUpLeft,
  Logout: IconLogout2,
  ArrowDownRight: IconArrowDownRight,
  CircleOff: IconCircleOff,
  Search: IconSearch,
  DashBoard: IconDashboard,
  MultiUsers: IconUsers,
  TableFilled: IconTableFilled,
  UserFilled: IconUserFilled,
}

type IIconKeys = keyof typeof Icons

export type { IIconKeys, TablerIconsProps }
