import {
  IconAffiliate,
  IconAlertCircle,
  IconArrowDown,
  IconArrowDownRight,
  IconArrowRight,
  IconArrowRoundaboutLeft,
  IconArrowUp,
  IconArrowUpLeft,
  IconArrowsRight,
  IconArrowsShuffle2,
  IconBook,
  IconBrandGithub,
  IconBrandGoogle,
  IconBrandTelegram,
  IconCalendar,
  IconCards,
  IconCaretDownFilled,
  IconCaretUpFilled,
  IconChalkboard,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconCircleOff,
  IconCopy,
  IconDashboard,
  IconDeviceDesktop,
  IconDots,
  IconDotsVertical,
  IconEye,
  IconFilter,
  IconFlask,
  IconGlobe,
  IconHandStop,
  IconLanguage,
  IconLifebuoy,
  IconLink,
  IconLoader2,
  IconLogout2,
  IconMail,
  IconMath,
  IconMaximize,
  IconMenu,
  IconMinus,
  IconMoodEmptyFilled,
  IconNavigation,
  IconPencil,
  IconPlayerPause,
  IconPlayerPlay,
  IconPlus,
  IconRefresh,
  IconSearch,
  IconSmartHome,
  IconStar,
  IconTableFilled,
  IconTrash,
  IconTypography,
  IconUserFilled,
  IconUsers,
  IconX,
  TablerIconsProps,
} from "@tabler/icons-react"

export const Icons = {
  Plus: IconPlus,
  Checked: IconCheck,
  Play: IconPlayerPlay,
  Copy: IconCopy,
  HandStop: IconHandStop,
  Delete: IconTrash,
  Navigation: IconNavigation,
  Menu: IconMenu,
  Pause: IconPlayerPause,
  FullScreen: IconMaximize,
  ArrowUp: IconArrowUp,
  ArrowDown: IconArrowDown,
  Email: IconMail,
  X: IconX,
  Loader: IconLoader2,
  Spinner: IconLoader2,
  Refresh: IconRefresh,
  Icon: IconCards,
  Home: IconSmartHome,
  About: IconArrowRoundaboutLeft,
  Document: IconBook,
  School: IconChalkboard,
  Contact: IconAffiliate,
  Github: IconBrandGithub,
  Google: IconBrandGoogle,
  SignatureArrow: IconArrowUpLeft,
  Logout: IconLogout2,
  ArrowDownRight: IconArrowDownRight,
  CircleOff: IconCircleOff,
  Eye: IconEye,
  Filter: IconFilter,
  Report: IconAlertCircle,
  Search: IconSearch,
  DashBoard: IconDashboard,
  MultiUsers: IconUsers,
  TableFilled: IconTableFilled,
  UserFilled: IconUserFilled,
  Minus: IconMinus,
  CaretUpFilled: IconCaretUpFilled,
  CaretDownFilled: IconCaretDownFilled,
  Support: IconLifebuoy,
  Link: IconLink,
  DotVertical: IconDotsVertical,
  Edit: IconPencil,
  Empty: IconMoodEmptyFilled,
  Send: IconBrandTelegram,
  Dot: IconDots,

  //Chevrons
  ChevronUp: IconChevronUp,
  ChevronDown: IconChevronDown,
  ChevronLeft: IconChevronLeft,
  ChevronRight: IconChevronRight,
  Calendar: IconCalendar,
  ArrowRight: IconArrowRight,
  ArrowsRight: IconArrowsRight,

  //Control
  Shuffle: IconArrowsShuffle2,
  Star: IconStar,
  Fullscreen: IconMaximize,

  //Subjects
  Math: IconMath,
  Literature: IconTypography,
  History: IconArrowRoundaboutLeft,
  Science: IconFlask,
  Languague: IconLanguage,
  Computer: IconDeviceDesktop,
  Geography: IconGlobe,
}

type IIconKeys = keyof typeof Icons

export type { IIconKeys, TablerIconsProps }
